<?php

namespace Database\Factories;

use App\Models\Reference;
use Grimzy\LaravelMysqlSpatial\Types\Point;
use Illuminate\Database\Eloquent\Factories\Factory;

class ReferenceFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var string
     */
    protected $model = Reference::class;

    /**
     * Define the model's default state.
     *
     * @return array
     */
    public function definition()
    {
        $programmes = [
            '1S',
            '3A',
            '3B',
            '3C',
            '3D',
            '3D',
            '3V',
            '3W',
            '3X',
            '4J',
            '4L',
            '4O',
            '4S',
            '4X',
            '5A',
            '5B',
            '5H',
            '5N',
            '5R',
            '5T',
            '5U',
            '5V',
            '5W',
            '5X',
            '5Z',
            '6W',
            '6Y',
            '7O',
            '7P',
            '7Q',
            '7X',
            '8R',
            '9A',
            '9G',
            '9H',
            '9J',
            '9K',
            '9L',
            '9M',
            '9N',
            '9Q',
            '9U',
            '9X',
            'A2',
            'A5',
            'A6',
            'AN',
            'AP',
            'BV',
            'BY',
            'C3',
            'C5',
            'C6',
            'C9',
            'CE',
            'CM',
            'CN',
            'CP',
            'CT',
            'CU',
            'CX',
            'D4',
            'D6',
            'DL',
            'DU',
            'E3',
            'E5',
            'E7',
            'EA',
            'EI',
            'EK',
            'EL',
            'EP',
            'ER',
            'ES',
            'ET',
            'EW',
            'EX',
            'EY',
            'EZ',
            'FF',
            'Gx',
            'Gx',
            'H4',
            'HA',
            'HB',
            'HC',
            'HH',
            'HI',
            'HK',
            'HL',
            'HP',
            'HR',
            'HS',
            'HZ',
            'IF',
            'J2',
            'J6',
            'J7',
            'JA',
            'JT',
            'JY',
            'KF',
            'LA',
            'LU',
            'LX',
            'LY',
            'LZ',
            'OA',
            'OD',
            'OE',
            'OH',
            'OK',
            'OM',
            'ON',
            'OZ',
            'P2',
            'P4',
            'P5',
            'PA',
            'PY',
            'PZ',
            'RF',
            'S2',
            'S5',
            'S7',
            'SM',
            'SP',
            'ST',
            'SU',
            'SV',
            'T2',
            'T3',
            'T5',
            'T8',
            'TA',
            'TF',
            'TG',
            'TI',
            'TJ',
            'TL',
            'TN',
            'TR',
            'TT',
            'TU',
            'TY',
            'TZ',
            'UK',
            'UN',
            'UR',
            'V2',
            'V3',
            'V4',
            'V5',
            'V6',
            'V7',
            'V8',
            'VE',
            'VK',
            'VR',
            'VU',
            'XE',
            'XT',
            'XU',
            'XW',
            'XY',
            'YA',
            'YB',
            'YJ',
            'YK',
            'YL',
            'YN',
            'YO',
            'YS',
            'YU',
            'YV',
            'Z2',
            'Z3',
            'Z6',
            'ZA',
            'ZB',
            'ZL',
            'ZP',
            'ZS',
            'ZZ',
        ];

        return [
            'reference' => $this->faker->numerify($this->faker->randomElement($programmes).'FF-####'),
            'name' => $this->faker->streetName().' '.$this->faker->randomElement(['park', 'national park', 'nature reserve']),
            'first_activation_date' => $this->faker->date(),
            'latest_activation_date' => $this->faker->date(),
            //'location' => new Point($this->faker->latitude(), $this->faker->longitude())
            'status' => $this->faker->randomElement(['active', 'deleted', 'national']),
        ];
    }
}
